### ISSUE TITLE
Help needed with Cyborg AMBX Lights on Android

### ISSUE THREAD

**Issue by ShivaNair2006** [gryphius/pycyborg#2]
Hi,

The instructions worked perfectly fine on a Linux/Openelec setup on Xtreamer Ultra. many Thanks.

I have replaced my Xtreamer Ultra Box to a new Minix Neo X8-H Plus running on Android (non rooted).
 I need you help to make the Mad Catz Cyborg amBX Gaming Lights (www.cyborggaming.com/prod/ambx.htm) work on the Android Box. (total 6 lights)
 I am on XBMC Kodi Helix 14.2 on Android Kitkat 4.4.2

 Please can you guide me to configure the Lights on the new Android box.

 Many thanks .

 Your help is greatly appreciated.

 Regards,
 Shiva

**Comment by gryphius** [comment]
Hi, sorry I don't have any experience with doing this kind of stuff on android. I guess you'd have to search for android ports of libusb and pyusb. I doubt this would work on a non-rooted device though.

**Comment by ShivaNair2006** [comment]
Thanks gryphius. 
Any link or guide that you can help me direct to will be much appreciated. (i am not a technical expert like you are hence this request :))

Many Thanks,
Shiva

**Comment by gryphius** [comment]
closing this as I'm not able to help here
