### ISSUE TITLE
Issues with OpenElec 6.0.3

### ISSUE THREAD

**Issue by alex-vision** [gryphius/pycyborg#3]
I followed the directions for installation on open elec.  Yet there were some differences from your instructions and I tried to cope with them as best as I could.  Im running openelec 6.0.3 on a raspberry pi 2. I still ran into some issues I was hoping you could help with.  I installed both pycyborg-master and pyusb-master to `/storage/.kodi/userdata` because `/storage/.xbmc/userdata/` is not used anymore, at least I think that's why I couldn't find it. Also the instructions call for you to navigate to `userdata/addon_data/service.multimedia.boblightd/` and create the boblight.conf file.  Well in my install that folder didn't exist, so I created it, and I created the boblight.conf file.  I added the content you had indicated to add, changing the text in line 7 from `output "/storage/.xbmc/userdata/pycyborg-master/boblight.py"` to `output "/storage/.kodi/userdata/pycyborg-master/boblight.py"`. I then followed the instructions to create a symlink and run the test file.  I was unable to get indentify.py to run.  This is the result of trying to run ./identify.py 

`OpenELEC2:~/.kodi/userdata/pycyborg-master # ./identify.py
Traceback (most recent call last):
  File "./identify.py", line 6, in <module>
    cyborgs=get_all_cyborgs()
  File "/storage/.kodi/userdata/pycyborg-master/pycyborg/__init__.py", line 185, in get_all_cyborgs
    devs=usb.core.find(find_all=True,idVendor=VENDOR,idProduct=PRODUCT)
  File "/storage/.kodi/userdata/pycyborg-master/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

Any thoughts? I have four sets of Cyborg gaming lights that are no longer compatible with my computer due to upgrades to windows 8.1 and windows 10, so I have just been storing them in my closet, but I would be incredibly grateful to you if you could help me out with this problem.

**Comment by gryphius** [comment]
> usb.core.NoBackendError: No backend available

This sounds like libusb is not installed (or pyusb doesn't find it). I haven't used OpenElec in years so I don't know how you would install this correctly. My raspberry pi 3 should arrive this week tho, I'll try to find out.

**Comment by alex-vision** [comment]
Ok. I'll check on that on my end. I'll see if I can manually install
libusb. I'm not very good with Linux so I may have to wait until you get it
up and running, but know that I am extremely interested in your results. I
have all these cyborg light collecting dust and I would love to use them
again. Thank you for taking the time to help out with this problem.

**Comment by gryphius** [comment]
@alex-vision I remembered that openelec needed a special hack to load libusb which didn't work anymore. This is now updated and I've adapted the openelec install docs as well.

My cyborg lamps now work on openelec 6.0.3 / raspberry pi 3.

Please update your pycyborg code and try again!

**Comment by alex-vision** [comment]
I updated my download of pycyborg, I had to chmod some files (probably because of the way I transferred them) and everything now works perfectly.  This is so great, thank you. I would love to donate some moneyto thank you for your time on this project, if you have paypal or something.

**Comment by gryphius** [comment]
glad to hear that it works for you as well! 

>  I would love to donate some money

this is very kind, but knowing that this code is useful to someone else is more than enough compensation :)
